#!/usr/bin/env bash
echo "Deploying cloud formation template..."

STACK_NAME="qs-standard-queue-stack"

root_path=$(realpath .)
template_path="cloudformation"
TEMPLATE_FILE="$root_path/$template_path/template.yml"

aws cloudformation deploy \
   --template-file $TEMPLATE_FILE \
#     --region eu-west-2 \
#     --stack-name $STACK_NAME 