#!/usr/bin/env bash
echo "Creating a new S3 bucket..."
# Create a new S3 bucket named "dm-new-bucket" in the "eu-west-2" region
# Check if bucket name is provided
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi
BUCKET_NAME=$1
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--region eu-west-2 \
--create-bucket-configuration="LocationConstraint=eu-west-2" \
--query Location \
--output text