#!/usr/bin/env bash
echo "Listing objects in an S3 bucket..."
# List objects in an S3 bucket
# Check if bucket name is provided
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi
BUCKET_NAME=$1
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--region eu-west-2 

